### ISSUE TITLE
SwiftMonkey cannot works on xCode 8.3

### ISSUE THREAD

**Issue by huming** [zalando/SwiftMonkey#27] opened 2017-04-10 06:40 UTC
SwiftMonkeyExample build success, but run test shows build failed. I upgrade Xcode from 7.3 to 8.3. I Before it can works. So anybody know why? 

Other build failed have not error detail.

**Comment by lasomethingsomething** [comment] 2017-04-27 07:39
Hello @huming, thank you for submitting this issue. Would you be able to submit a PR to address it?

cc @DagAgren

**Comment by huming** [comment] 2017-04-28 10:16
hi, LappleApple, thanks for your response. What is PR?

**Comment by lasomethingsomething** [comment] 2017-04-28 10:24
@huming pull request

**Comment by wojciechczerski** [comment] 2017-05-01 20:44
I did a research on this issue and what I have found is that it only concerns the `SwiftMonkeyExample` and it has no relation with the `SwiftMonkey` framework. _Most probably_ the source of the problem is a **bug in XCTest**. 

The UI tests are failing with an assertion `Failed to get snapshot within 15.0s`. This error has been already reported:
- https://forums.developer.apple.com/thread/75413
- https://github.com/fastlane/fastlane/issues/6610
- https://github.com/facebook/WebDriverAgent/issues/474
- http://howtodevelop.eu/question/xcode-ios-xcode-uitest-unable-to-test-wechat-login,145573

In case of the `SwiftMonkeyExample` target, the problem is caused by the _Switches!_ section of the table view. It seems that the current configuration (**4 rows** with **5** `UISwitch` elements each) is too complicated for the snapshot creation to finish within 15 seconds. However I did observe that using **10 rows** with **4 elements** configuration will work just fine without producing the assert.

**Comment by wojciechczerski** [comment] 2017-05-25 16:46
I've created a pull request (https://github.com/zalando/SwiftMonkey/pull/31) that addresses this issue.

**Comment by wojciechczerski** [comment] 2017-05-30 20:29
Fixed in https://github.com/zalando/SwiftMonkey/pull/31.

**Closed as completed by wojciechczerski** 2017-05-30 20:29 UTC
