### ISSUE TITLE
Test in Specified app

### ISSUE THREAD

**Issue by mengxun** [zalando/SwiftMonkey#41] opened 2017-09-04 06:05 UTC
Dear,
This is a magical tool, but I find that the monkey often test outside of the app, how to make sure the monkey is running in the app which I specified.

Look forward to your reply

                                                                                                                           Your Dear UserA

**Comment by wojciechczerski** [comment] 2017-09-05 23:21
Hello there, and than you for the feedback!

Could you please describe your issue a bit more precisely? In particular I am not sure what does _running outside the specified app_ means.

**Comment by mengxun** [comment] 2017-09-06 02:31
Oh, sorry for hear that, my English is not good, so please forgive me.
Running outside the specified app means that the monkey maybe run on the springboard, it taps anywhere on iPhone screen, so the monkey runs in other apps sometimes not in my app. I think that is unnormal, but I have no idea to avoid. I want to know how to let the monkey only run in my app. 

😢

**Comment by singh88** [comment] 2017-09-06 18:45
possible duplicate of https://github.com/zalando/SwiftMonkey/issues/4

**Closed as completed** 2017-09-21 21:02 UTC
Labels: duplicate
